version: '3.8'

services:
  # MSSQL service
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    hostname: "mssql"
    environment:
      MSSQL_SA_PASSWORD: "Admin123&"
      ACCEPT_EULA: "Y"  # Accept the end-user license agreement
    ports:
      - "1434:1433" 

  # EngrafoCA Web App
  engrafoca:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: engrafoca
    ports:
      - "8081:81"
    depends_on:
      - mssql
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"