// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Documentation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documentations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cec2f141-3f12-4e61-881c-84eb3ff8bf82"),
                            Created = new DateTime(2024, 5, 13, 0, 10, 7, 426, DateTimeKind.Local).AddTicks(2500),
                            LastModified = new DateTimeOffset(new DateTime(2024, 5, 13, 0, 10, 7, 426, DateTimeKind.Unspecified).AddTicks(2562), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Doc1"
                        },
                        new
                        {
                            Id = new Guid("f8336276-b4f3-418f-9057-8bfe05748a10"),
                            Created = new DateTime(2024, 5, 13, 0, 10, 7, 426, DateTimeKind.Local).AddTicks(2597),
                            LastModified = new DateTimeOffset(new DateTime(2024, 5, 13, 0, 10, 7, 426, DateTimeKind.Unspecified).AddTicks(2599), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Doc2"
                        },
                        new
                        {
                            Id = new Guid("0dcf6968-b5f3-4577-81fd-2fbc3bd84ba4"),
                            Created = new DateTime(2024, 5, 13, 0, 10, 7, 426, DateTimeKind.Local).AddTicks(2603),
                            LastModified = new DateTimeOffset(new DateTime(2024, 5, 13, 0, 10, 7, 426, DateTimeKind.Unspecified).AddTicks(2605), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Doc3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
